### ISSUE TITLE
Add “value” field to “<dimension-unit>”

### ISSUE THREAD

**Issue by SofyaPovarova** [w3c/webref#1092]
The “\<dimension-unit\>” entry from [css-value-5.json](https://github.com/w3c/webref/blob/curated/ed/css/css-values-5.json) doesn’t have a value:
```
{
      "name": "<dimension-unit>",
      "prose": "The <dimension-unit> production matches a literal \\"%\\" character (that is, a <delim-token> with a value of \\"%\\") or an ident whose value is any of the CSS units for <length>, <angle>, <time>, <frequency>, or <flex> values (such as px or ms).",
      "type": "type"
}
```
I think this could be fixed in the following way. First, fix definitions of “\<length\>”, “\<angle\>”, “\<time\>”, “\<frequency\>”, and “\<flex\>” by extracting their unit descriptions into separate values. This would be closer to the [specification](https://drafts.csswg.org/css-values-4/#lengths) and would help to add the “value” field to the “\<dimension-unit\>” entry
Here’s a simplified example for “\<flex\>”. Current content:
```
{
      "name": "<flex>",
      "values": [
        {
          "name": "fr",
          "value": "fr"
        }
      ]
}
```
Suggested change:
```
{
      "name": "<flex>",
      "value": "<number><flex-unit>"
    },
    {
      "name": "<flex-unit>",
      "values": [
        {
          "name": "fr",
          "value": "fr"
        }
      ]
 } 
```
After doing the same with “\<length\>”, “\<angle\>”, “\<time\>”, and “\<frequency\>”, we’ll be able to fix “\<dimension-unit\>” as follows:
```
{
      "name": "<dimension-unit>",
      "prose": "The <dimension-unit> production matches a literal \\"%\\" character (that is, a <delim-token> with a value of \\"%\\") or an ident whose value is any of the CSS units for <length>, <angle>, <time>, <frequency>, or <flex> values (such as px or ms).",
      "type": "type",
      "value": "'%' | <length-unit> | <angle-unit> | <time-unit> | <frequency-unit> | <flex-unit>"
}
```

Would you agree with such an update? I'm happy to submit a pull request if you want.
Thank you

**Comment by tidoust** [comment]
As in #1093, ideally, these updates should be brought to the CSS Values specification directly. That is a bit more convoluted than in #1093, but doable :)

For instance, you would need something like the following (the double `<<` and `>>` are for Bikeshed to perform some auto-linking magic, see [Wrapper syntax](https://speced.github.io/bikeshed/#autolink-wrappers)) for `<dimension-unit>`:

```html
<pre class=prod>
  <<dimension-unit>> = '%' | <<length-unit>> | <<angle-unit>> | <<time-unit>> | <<frequency-unit>> | <<flex-unit>>
</pre>
```

**Comment by SofyaPovarova** [comment]
Ok, it definitely looks manageable. Thanks again for the direction!
