### ISSUE TITLE
Missing HTML heading defined thing

### ISSUE THREAD

**Issue by marcoscaceres** [w3c/webref#114]
With the ol' Shepherd data, it was possible to reference, for example, [=link type "manifest"=] - which is defined in the HTML spec in a H5 (and exported). 

As such, right now, I've got a bunch of broken links over in the Web Manifest spec that are trying to link to [=link type "manifest"=]. I'm wondering how we should deal with those?

 * add support for headings as definitions in Webref?
 * fix the HTML spec to add `<dfn data-export="">`?
 * Something else?

**Comment by marcoscaceres** [comment]
Here is the link to the HTML spec:
https://html.spec.whatwg.org/multipage/links.html#link-type-manifest

Here is the markup there:

```
<h5 id="link-type-manifest"><span class="secno">4.6.6.10</span> Link type "<dfn><code>manifest</code></dfn>"<a href="#link-type-manifest" class="self-link"></a></h5>
```

**Comment by tidoust** [comment]
> add support for headings as definitions in Webref?

To clarify the request, are you looking for a place where headings are listed? Or is it specifically about integrating the headings into the dfns extracts?

If the former, I note Webref has them already in dedicated extracts. For instance, the heading you mention can be found in [`ed/headings/html.json`](https://github.com/w3c/webref/blob/master/ed/headings/html.json) at [line 1482](https://github.com/w3c/webref/blob/master/ed/headings/html.json#L1482).

If the latter, we defined the dfns extracts as: "anything in a `<dfn>`", but that definition could perhaps rather be "anything that can be referenced in a spec". That seems doable.


> fix the HTML spec to add <dfn data-export="">?

I would rather adapt the dfns extraction logic than start wrapping headings in `<dfn>` simply to have them picked up by that logic. We take for granted that headings are always exported.

By the way, I note that neither dfns nor headings extracts preserve the markup for the linking text. Ideally, `[=link type "manifest"=]` would get expanded to something like `<a href="...">link type "<code>manifest</code>"</a>`, but the `<code>` info does not appear in the extracts. I suppose that was the case in Shepherd as well.

**Comment by dontcallmedom** [comment]
The ultimate goal should be to fix the HTML spec, which we've started doing e.g. https://github.com/whatwg/html/pull/5694
But a short-term fix would involve [patching Reffy](https://github.com/w3c/reffy/blob/7ca4afbd8fb80d40217d3fffb4df529814ddf427/src/browserlib/extract-dfns.mjs#L151) - looking at [the HTML definitions in webref](https://github.com/w3c/webref/blob/master/ed/dfns/html.json), they already includes "link-type-manifest", but it's marked as private - I don't know if we can safely assume that all the defined terms in headings in the HTML specs are meant to be exported; if they do, it should be a very simple fix

**Comment by tidoust** [comment]
> I don't know if we can safely assume that all the defined terms in headings in the HTML specs are meant to be exported; if they do, it should be a very simple fix

The entry would still be for the "manifest" term in the heading, not for the heading itself, which is what I understand @marcoscaceres needs here.

**Comment by dontcallmedom** [comment]
> The entry would still be for the "manifest" term in the heading, not for the heading itself, which is what I understand @marcoscaceres needs here.

It is for "manifest" (that's what the linkingText is set to) - the pattern `<hx id=foo>The <dfn>bar</dfn></hx>` is one already recognized by reffy

**Comment by dontcallmedom** [comment]
Hmm... Good point; I guess we had talked about exposing spec headings as possible end point for autolinks, but I don't think that has happened yet. 

(I haven't checked if the initial intent is really to link to the section vs the defined term though)

**Comment by marcoscaceres** [comment]
@tidoust  wrote
> To clarify the request, are you looking for a place where headings are listed? Or is it specifically about integrating the headings into the dfns extracts?

integrating the headings into the dfns extracts

> I would rather adapt the dfns extraction logic than start wrapping headings in <dfn> simply to have them picked up by that logic. We take for granted that headings are always exported.

I'm a bit worried about that... we might end up with duplicate definitions. 
 
> By the way, I note that neither dfns nor headings extracts preserve the markup for the linking text. Ideally, [=link type "manifest"=] would get expanded to something like <a href="...">link type "<code>manifest</code>"</a>, but the <code> info does not appear in the extracts. I suppose that was the case in Shepherd as well.

Correct, though not a big deal. However, it might be a nice thing to have.

@dontcallmedom wrote:
> I don't know if we can safely assume that all the defined terms in headings in the HTML specs are meant to be exported; if they do, it should be a very simple fix

Agree. I'd prefer we export them explicitly. 

@tidoust wrote:
> The entry would still be for the "manifest" term in the heading, not for the heading itself, which is what I understand @marcoscaceres needs here.

Kinda right... specifically, `link type "manifest"`... I don't mind just sending a PR to HTML to explicitly export it (like you are doing in whatwg/html#5694). 

Should I just add `<dfn export>` to the `<h5>link type "manifest"` for now? Seems like the safest option.

**Comment by marcoscaceres** [comment]
Hmm.. looks like best I can do is:

```HTML
<h5>Link type "<dfn export data-lt="link type manifest"><code data-x="rel-manifest">manifest</code></dfn>"</h5>
```

I might try that and see what the HTML folks say.

**Comment by marcoscaceres** [comment]
Sent https://github.com/whatwg/html/pull/6445

**Comment by marcoscaceres** [comment]
Closing, as attribute value exports are now done properly in HTML.
