### ISSUE TITLE
Remove "local" in RTC"Local"SessionDescriptionInit 

### ISSUE THREAD

**Issue by jarrodcolburn** [w3c/webref#1155]
Problem: `RTCLocalSessionDescriptionInit` class for "local" seems unneeded. 

I think `RTCSessionDescriptionInit` would suffice. 
<hr>
Recommendations:

* Remove `RTCLocalSessionDescriptionInit`.  All instances of `RTCLocalSessionDescriptionInit` become `RTCSessionDescriptionInit`.

* (maybe less good)...  If `RTCLocalSessionDescriptionInit` is needed, extend it from `RTCSessionDescriptionInit`, and create new "remote" class `RTCRemoteSessionDescriptionInit` for consistency. 

<hr>

For context, I don't see where `RTCLocalSessionDescriptionInit` is used in the MDN docs either for either:

[setLocalDescription method](https://developer.mozilla.org/en-US/docs/Web/API/RTCPeerConnection/setLocalDescription)

[localDescription attribute](https://developer.mozilla.org/en-US/docs/Web/API/RTCPeerConnection/localDescription)

**Comment by tidoust** [comment]
Would you mind raising the issue against the spec repository [w3c/webrtc-pc](https://github.com/w3c/webrtc-pc/)? Webref merely documents the Web IDL as it exists in the underlying spec, see [`RTCLocalSessionDescriptionInit`](https://w3c.github.io/webrtc-pc/#webidl-648942176). Said differently, the spec is the source, Webref is just the messenger ;)

For what it's worth, looking into that repository, it seems that the creation of the `RTCLocalSessionDescriptionInit` dictionary was triggered by the need to have a `required` attribute in one case but not in the other case, see https://github.com/w3c/webrtc-pc/issues/2528. That is, to my understanding, the duplication fixes a Web IDL constraint error (a non optional dictionary parameter must have at least one required member).

I note that MDN does not really document `RTCSessionDescriptionInit` either, it just mentions it with a "documentation not yet written" link.

**Comment by jarrodcolburn** [comment]
Will do. And thank you so much for the context @tidoust , that helped a ton as I'm not really familiar with these repos. Actually, I opened this issue because the [Dart IDL bindings package](https://pub.dev/packages/web) uses this, via the [node IDL bindings package](https://www.npmjs.com/package/@webref/idl/v/3.43.1), so it's like the "messenger of the messenger of the messenger".

**Comment by jarrodcolburn** [comment]
Closing

**Comment by jarrodcolburn** [comment]
Opening https://github.com/w3c/webrtc-pc/issues/2940 on webrtc-pc repo as suggested. thanks again
