### ISSUE TITLE
Extract HTML/SVG tagname-interface mapping

### ISSUE THREAD

**Issue by saschanaz** [w3c/webref#120]
Background: https://github.com/saschanaz/types-web/issues/76

It would probably require some changes to the spec files.

**Comment by tidoust** [comment]
Reffy has custom code to parse [CSS property definitions](https://drafts.csswg.org/css2/#property-defs) to generate the css extracts. It makes sense to me to do the same thing with the HTML [element definitions](https://html.spec.whatwg.org/multipage/dom.html#element-definitions), starting with scraping the [DOM interface](https://html.spec.whatwg.org/multipage/dom.html#concept-element-dom).

That should not require changes to the spec files, but scraping rules will obviously have to follow possible spec conventions changes. The following seems to work:

1. Retrieve all `<dl>` element definitions with `document.querySelectorAll('.element')`
2. Look for a `<dt>` whose text is `DOM interface:`
3. Following `<dd>`:
    * has a `<pre>` with the IDL of the interface (e.g. [`<p>`](https://html.spec.whatwg.org/multipage/grouping-content.html#the-p-element:concept-element-dom)). Either we fire the Web IDL parser at it, or we look for `interface [interface name]`.
    * OR starts with `Uses [interface name]` (e.g. [`<samp>`](https://html.spec.whatwg.org/multipage/text-level-semantics.html#the-samp-element:concept-element-dom) or [`<col>`](https://html.spec.whatwg.org/multipage/tables.html#the-col-element:concept-element-dom)).

**Comment by dontcallmedom** [comment]
+1 to that approach; I think it might be useful to at least document with the upstream spec our intent to rely on these conventions (ideally, these conventions would end up being enforced there)

**Comment by tidoust** [comment]
Reffy now creates extracts for the mapping between HTML/SVG tag names and their IDL interface under an `elements` folder, see:
https://github.com/w3c/webref/tree/master/ed/elements

Specs for which this currently works are:
- [SVG 2](https://svgwg.org/svg2-draft/) (and SVG 1.1, same ED in practice)
- [css-masking-1](https://drafts.fxtf.org/css-masking-1/)
- [filter-effects-1](https://drafts.fxtf.org/filter-effects-1/)
- [HTML](https://html.spec.whatwg.org/multipage/)
- [SVG Animations](https://svgwg.org/specs/animations/)

Closing this issue, but feel free to reopen or create a new issue if there are other specs to consider. Logic unfortunately needs to be adjusted on a spec per spec basis for now.

Also, note logic only extracts the interface name. It could perhaps be extended to extract other information (context, content model, link to accessibility specs, etc.), but note that there are always exceptions-to-the-rule that make it hard to create machine-readable information.

Talking about exceptions-to-the-rule, I note that the `discard` element in SVG Animations is not associated with any interface:
https://github.com/w3c/webref/blob/ebe063c26b33afb1dd0ff37ae9ad70b8d9fbad77/ed/elements/svg-animations.json#L16

**Comment by saschanaz** [comment]
Thank you! Maybe it's time to talk about making the specs more machine friendly 🤔

**Comment by tidoust** [comment]
Possibly but it will probably be useful to understand what a machine is going to do with that info to assess what improvements could be made to the specs.

For instance, you could imagine a machine-readable way to express the categories and contexts for a [`meta` element in HTML](https://html.spec.whatwg.org/multipage/semantics.html#the-meta-element) but then the prose is already close to code...

In other cases, it may be possible to split things up between machine-readable and human-readable. For instance, the note on the `title` attribute for the [`style` element in HTML](the https://html.spec.whatwg.org/multipage/semantics.html#the-style-element) could perhaps be ignored initially from a machine perspective.

**Comment by saschanaz** [comment]
I just found that it's not being released to npm, could we release something like `@webref/elements`?

**Comment by tidoust** [comment]
> I just found that it's not being released to npm, could we release something like `@webref/elements`?

Sure. Let's re-open the issue. I'll create the appropriate release logic.

**Comment by tidoust** [comment]
Release logic should now be in place. First version of [`@webref/elements` package](https://www.npmjs.com/package/@webref/elements) just released.

**Comment by foolip** [comment]
Awesome! I think we'll find use for this in BCD to check that interfaces aren't supported before their elements are.

**Comment by saschanaz** [comment]
> Talking about exceptions-to-the-rule, I note that the `discard` element in SVG Animations is not associated with any interface:

BTW it's a spec bug, opened a PR https://github.com/w3c/svgwg/pull/855
