### ISSUE TITLE
cancel event doesn't bubble

### ISSUE THREAD

**Issue by dontcallmedom** [w3c/webref#1212]
see https://github.com/orgs/mdn/discussions/665#discussioncomment-9125774

**Comment by tidoust** [comment]
But the spec says it does, at least for input elements?
https://html.spec.whatwg.org/multipage/input.html#common-input-element-apis:event-cancel

**Comment by dontcallmedom** [comment]
but not on dialog elements? https://html.spec.whatwg.org/multipage/interactive-elements.html#the-dialog-element:event-cancel

if so, not sure how we can represent this usefully…

**Comment by dontcallmedom** [comment]
hmm... I misread, it's on the CloseWatcher interface that it doesn't bubble (it couldn't anyway)

**Comment by dontcallmedom** [comment]
now there is a question as to why we don't detect the cancel event on CloseWatcher

**Comment by dontcallmedom** [comment]
sorry, I'm confusing two data points:
* https://html.spec.whatwg.org/multipage/interactive-elements.html#the-dialog-element:event-canceI says it doesn't bubble on dialog
* https://html.spec.whatwg.org/multipage/interaction.html#the-closewatcher-interface:event-cancel-4 says that it doesn't bubble on CloseWatcher (which we're not tracking at all)

**Comment by tidoust** [comment]
> now there is a question as to why we don't detect the cancel event on CloseWatcher

That's because the `data-dfn-for` attribute needs fixing in the [definition of `cancel`](https://html.spec.whatwg.org/multipage/indices.html#event-cancel) in the HTML spec. It should be `data-dfn-for="CloseWatcher,HTMLElement"` and not only `data-dfn-for="HTMLElement"`.

(Same problem in the definition of the `close` event apparently, which should have `data-dfn-for="CloseWatcher,HTMLElement,MessagePort"`).

**Comment by dontcallmedom** [comment]
I guess we don't have but could benefit from a system that detects EventTarget interfaces for which is there is no matching known events?

**Comment by tidoust** [comment]
Yes, I was thinking about that as well. I created #1216 to track this.

**Comment by tidoust** [comment]
Closing as addressed. The `cancel` event entry now correctly reports that the event bubbles on `HTMLInputElement`, does not bubble on `HTMLDialogElement`, and also fires at `CloseWatcher` where bubbling does not mean anything. The update was released in v1.11.0 of `@webref/events`.
