### ISSUE TITLE
how to get parsed idl json like in idlparsed 

### ISSUE THREAD

**Issue by areuu** [w3c/webref#1236]
Hi, I'm look a idl file named webnn.idl, I also look idlparsed/webnn.json. 
in idl file 
```
dictionary MLArgMinMaxOptions {
  sequence<[EnforceRange] unsigned long> axes;
  boolean keepDimensions = false;
  boolean selectLastIndex = false;
};
```
In webnn.json, I can't find any about `MLArgMinMaxOptions` info. 

It seems outdated, how can I get new parsed json file?

**Comment by areuu** [comment]
I try to use `webidl2js` to parse webidl to get a json file, but result not like idlparsed 
```
const fs = require('fs');
const webidl2 = require('webidl2');
const webidl = fs.readFileSync('/home/uuu/repo/webref/tr/idl/webnn.idl', 'utf8');
const parsedIDL = webidl2.parse(webidl);
console.log(parsedIDL);
```
result is 
```
[
  Mixin {
    members: [ [Attribute] ],
    extAttrs: ExtendedAttributes(0) []
  },
  Includes { extAttrs: ExtendedAttributes(0) [] },
  Includes { extAttrs: ExtendedAttributes(0) [] },
  Enum {
    values: [ EnumValue {}, EnumValue {} ],
    extAttrs: ExtendedAttributes(0) []
  },
  Enum {
    values: [ EnumValue {}, EnumValue {}, EnumValue {} ],
    extAttrs: ExtendedAttributes(0) []
  },
  Dictionary {
    members: [ [Field], [Field] ],
    extAttrs: ExtendedAttributes(0) []
  },
...
```

**Comment by dontcallmedom** [comment]
AFAICT, `idlparsed/webnn.json` in the curated branch has [info about `MLArgMinMaxOptions`](https://github.com/w3c/webref/blob/c7b5ce80022a3ccebbe5f1de7a1897be732190d3/ed/idlparsed/webnn.json#L1021).

the JSON file generated in idlparsed is not the simple serialization of webidl2.js - it is a [custom one](https://github.com/w3c/reffy/blob/main/src/postprocessing/idlparsed.js) that has proved more useful in our re-use of the data.

**Comment by areuu** [comment]
Oh, thank you for your reply, the data is very nice.
