### ISSUE TITLE
[CSS] Inconsistent / Conflicting value syntaxes through specs

### ISSUE THREAD

**Issue by Sharktheone** [w3c/webref#1308]
I noticed that some specs define conflicting properties, for instance `justify-content` is defined in [`css-align.json`](https://github.com/w3c/webref/blob/main/ed/css/css-align.json) and [`css-flexbox.json`](https://github.com/w3c/webref/blob/main/ed/css/css-flexbox.json)
[`css-align.json`](https://github.com/w3c/webref/blob/8a2ab49a7e8e6f02ef2211d651e9fe38bccf3581/ed/css/css-align.json#L33) defines the property's syntax like this: `"normal | <content-distribution> | <overflow-position>? [ <content-position> | left | right ]"`
However [`css-flexbox.json`](https://github.com/w3c/webref/blob/8a2ab49a7e8e6f02ef2211d651e9fe38bccf3581/ed/css/css-flexbox.json#L236) defines it like the following: `"flex-start | flex-end | center | space-between | space-around"`

Specs: 
- https://drafts.csswg.org/css-align-3/#align-justify-content
- https://drafts.csswg.org/css-flexbox-1/#justify-content-property
       
       
There are many more properties, even properties like `width`, `height` or `margin`.

How should an script that reads all properties decide what definition to use? I don't think a simple priority thing between specs works. 
([Here](https://github.com/gosub-browser/gosub-engine/tree/229f88d2ec97f09bf8e1ea03bc2eb5b1efdca1af/crates/gosub_styling/tools/generate_definitions) is the script I mentioned)

MDN just takes the last spec that defines the property and uses it as the syntax, but it doesn't really work out at all times, for example sometimes it uses definitions from specs that aren't ready for implementation.

My solution would be to write patches for all properties, or introduce an field for those properties that are conflicting, that says which property should be used.

The best solution would probably be to write patches, should I open an PR to add those patches to this repository, once I have them finished?

I'm not sure if these conflicts are an problem with the specs, but it seems a bit like it. I assume that normally when there is an conflict the older definition gets deleted or something.

I didn't find any other issue that had this topic, so point me out to them if I missed them. I'm also not sure, if I'm doing something wrong interpreting these json files.

**Comment by tidoust** [comment]
In short, the patches and the data without conflicts exist already, you're just looking at the wong place!

As noted in the [README](https://github.com/w3c/webref/?tab=readme-ov-file#description), the `main` branch contains raw extracts from the specs themselves, crawled every 6 hours. The only way to patch them is to patch the specs.

There is a patching mechanism in place, used to produce the `curated` branch. For CSS extracts, that patching consists of [individual patches per spec](https://github.com/w3c/webref/tree/main/ed/csspatches) and of a [script that drops duplicates](https://github.com/w3c/webref/blob/main/tools/drop-css-property-duplicates.js) (for example, that's where you'll find a rule that says that definitions in `css-align` trump those in `css-flexbox`).

Data curation provides the [guarantees detailed in the README](https://github.com/w3c/webref/?tab=readme-ov-file#css-extracts). These guarantees are enforced by tests (when a test fails, further updates on the curated branch are delayed until someone updates the patches). In other words, you need the [curated CSS extracts](https://github.com/w3c/webref/tree/curated/ed/css), and not the raw ones.

In an ideal world and/or on a longer term basis, specs would not introduce conflicts, and no patching would be needed, but we don't yet live in that world...

**Comment by Sharktheone** [comment]
Ah, thanks. I read about the `curated` branch, but forgot about it. I'm applying the patches in `/ed/csspatches/` but not using the script that drops the duplicates. I'll try now  with the curated ones. I hope that resolves the issues.

**Comment by Sharktheone** [comment]
Yup, seems to work. Thanks!

**Comment by Sharktheone** [comment]
I think, this is still a problem, even though a bit different. Duplicate values that are in the `"values"` section of a property for example don't get detected.

So on the `curated` branch there are still some duplicates, for instance `fit-content()`:
- [`css-sizing.json`](https://github.com/w3c/webref/blob/5975342a6e83ec5c2219b63945673a47d6cc1b4b/ed/css/css-sizing.json#L49): `fit-content(<length-percentage [0,∞]>)`
- [`css-grid.json`](https://github.com/w3c/webref/blob/5975342a6e83ec5c2219b63945673a47d6cc1b4b/ed/css/css-grid.json#L88): `fit-content( <length-percentage> )`

Or `<content-list`:
- [`css-content.json`](https://github.com/w3c/webref/blob/5975342a6e83ec5c2219b63945673a47d6cc1b4b/ed/css/css-content.json#L44): `[ <string> | <image> | <attr()> | contents | <quote> | <leader()> | <target> | <string()> | <content()> | <counter> ]+`
- [`css-gcpm.json`](https://github.com/w3c/webref/blob/5975342a6e83ec5c2219b63945673a47d6cc1b4b/ed/css/css-gcpm.json#L126): `[ <string> | <counter()> | <counters()> | <content()> | <attr()> ]+`

I don't know if I'm missing something again, like last time, that's totally possible.

**Comment by tidoust** [comment]
> So on the `curated` branch there are still some duplicates, for instance `fit-content()`:

The values that appear in the `"values"` section of a property are scoped to that property. They do not define a name in the generic namespace and therefore do not introduce duplicates. Today, there is no generic `fit-content()` function defined anywhere. There are different `fit-content()` functions, one for each property. The syntax may be the same, but the meaning may differ based on the underlying context.

More generally speaking, I'm afraid that the values that appear in the `"values"` section of a property are typically not what they seem to be. They come with no guarantees and have characteristics that make them impractical for most usages:
1. The list is not the result of processing the syntax of the underlying property value. The list is whatever the spec decided to document for that property, usually to explain some specific meaning in the context of the underlying property. Some values that you might expect may be missing as a result.
2. Values are not necessarily *atomic* either. A value there may be a chunk of the initial syntax cut at arbitrary positions, not a single type or function. Whatever the spec contains.
3. As said, they do not reference generic types or functions, but define contextual ones. For example, the definition of `<content-list>` for the `content` property is different from the (generic) one in the css-gcpm spec. Now, it's quite possible that some actually *proxy* a generic type or function. The whole thing is a bit clunky. Again, whatever the spec contains ;)

**Comment by Sharktheone** [comment]
Ah, okay. Thanks for the detailed explanation. I guess, we'll have to change how we interpret those values then.

Initially, I was not using those values at all, since I thought they are only documentation for some of the values that the property has, but some of the functions and definitions were missing then, so we needed to actually use those, but it wasn't clear that those were scoped.

So, thanks again for your time!
