### ISSUE TITLE
xr-standard is missing from GamepadMappingType in @webref/idl

### ISSUE THREAD

**Issue by saschanaz** [w3c/webref#131]
Currently this is removed from the IDL package [because of conflict](https://github.com/immersive-web/webxr-gamepads-module/issues/35). This is supported from Firefox/Chrome (or at least exists in their source code) so I think this should be added again, maybe in Gamepad IDL.

**Comment by saschanaz** [comment]
Or maybe just wait for https://github.com/w3c/gamepad/pull/146 👍

**Comment by foolip** [comment]
Was this fixed by https://github.com/w3c/webref/pull/142

**Comment by saschanaz** [comment]
Oops, yup.
