### ISSUE TITLE
Provide XSLTProcessor

### ISSUE THREAD

**Issue by saschanaz** [w3c/webref#155]
https://wiki.whatwg.org/wiki/DOM_XSLTProcessor (https://github.com/whatwg/dom/issues/181)

I think it's the only missing interface that doesn't belong to any real spec.

**Comment by foolip** [comment]
I've added this and a lot of other things which are implemented in one or more browsers in https://github.com/foolip/mdn-bcd-collector/tree/main/custom-idl. `console.timeStamp()` in console.idl is another example.

If there's a need for this non-standard IDL outside of mdn-bcd-collector, how about publishing it to a package similar to `@webref/idl`?

Putting it *in* webref would have certain benefits for maintaining it, but would also be a bit random. @dontcallmedom WDYT?

**Comment by saschanaz** [comment]
I somehow have considered the DOM wiki page as a semi-spec and just parsed it as ReSpec (it works). Could we also do the same here?

**Comment by foolip** [comment]
I'm not sure, I don't think it belongs in browser-specs, but maybe it could be hacked in as an extra data source in Reffy?

How about all the other non-standard IDL though, is that not interesting, is it just `XSLTProcessor` you're missing now?

**Comment by saschanaz** [comment]
Others are not widely implemented, so far this is the only missing one in types-web not filtered out by BCD support data when I remove all local IDLs.

**Comment by dontcallmedom** [comment]
given that `XSLTProcessor` has a reasonably clear (if pretty slow) standardization path, I think maintaining it in webref as a patch with a link to https://github.com/whatwg/dom/issues/181 would seem appropriate to me. I'm not convinced that parsing it out of the WHATWG wiki brings a lot of value (the only changes that I've happened in the wiki in the past 5 years where WebIDL-maintenance related), and it would likely break a lot of assumptions from a browser-spec perspective. If we want to avoid duplicating the maintenance until this lands in the DOM spec, we could get the WHATWG wiki to point to the webref patch.

I think the more general case of https://github.com/foolip/mdn-bcd-collector/tree/main/custom-idl would need more discussion - in particular, I don't think single-browser IDL customization should be added en masse to webref.

**Comment by foolip** [comment]
Maybe we should just send a PR to DOM to add the interfaces and algorithms that are just TODOs, pushing the problem one level down.

**Comment by saschanaz** [comment]
Or opening a WICG repo? 🤔

**Comment by foolip** [comment]
I added it to DOM in https://github.com/whatwg/dom/pull/972 so it should reach webref soon.

**Comment by dontcallmedom** [comment]
https://github.com/w3c/webref/blob/master/ed/idlnames/XSLTProcessor.idl is in, should make it to the package tomorrow
