### ISSUE TITLE
Push tags?

### ISSUE THREAD

**Issue by saschanaz** [w3c/webref#156]
I'm not using the tags, but somehow noticed that the latest tag is not the latest release. Is it expected to be updated?

**Comment by tidoust** [comment]
The use of releases was more the result of trying things out than of a willingness to create releases in the first place. I deleted the releases that had been created to get back to a tag-only situation. That should be enough for now.

We may create real releases later on, typically if we want to publish the contents of the package as a zip on GitHub, as opposed to the contents of the whole repo.

**Comment by foolip** [comment]
I think the question was about tags rather than releases. GitHub releases does create tags, but one can have tags with no GitHub release associated.

Having those tags is useful for a human figuring out what an npm package was create from.

**Comment by tidoust** [comment]
I'm not sure I understand the issue then. The release job creates a tag when a package is published in particular:
https://github.com/w3c/webref/tags

**Comment by foolip** [comment]
OK, I didn't actually confirm myself but just assumed a tag was missing :)

@saschanaz is there a tag missing?

**Comment by saschanaz** [comment]
Hmm, I think I saw releases instead then. Closing since all the tags are there.

**Comment by tidoust** [comment]
> Hmm, I think I saw releases instead then

Right, for the sake of clarity, there were releases on top of tags, and I deleted them.
