### ISSUE TITLE
SupportedType is used as argument but not declared

### ISSUE THREAD

**Issue by jodinathan** [w3c/webref#269]
Can't seem to find the declaration of ```SupportedType``` however, it is used in the interface DOMParser: https://github.com/w3c/webref/blob/0128e8f1ba0a91298d2ae633c8d345cb3f5bfae4/tr/idl/DOM-Parsing.idl#L9

is this expected?

**Comment by dontcallmedom** [comment]
we only provide consistency guarantees on the `webref/ed` tree (where `SupportedType` has been renamed to the well-defined `DOMParserSupportedType` and the interface itself been moved to the HTML standard)

At the moment, I wouldn't recommend working on top of `webref/tr`. @tidoust maybe we should emphasize that somehow in the README?

**Comment by dontcallmedom** [comment]
in the general, you'll get the highest level of guarantees from the data in the [NPM package](https://www.npmjs.com/package/@webref/idl)

**Comment by tidoust** [comment]
> Can't seem to find the declaration of SupportedType [...] is it expected?

It is not fantastic but it is "expected" in the sense that the (outdated) /TR version of DOM Parsing and Serialization uses a weird `extraidl` class instead of `idl` for the declaration of the enumeration, and thus the crawler misses the definition. We could perhaps extend the crawler to also extract `pre` sections that have an `extraidl` class, but then the right fix would be to publish a new Working Draft of the spec to correctly flag the IDL section as `idl`.

> we only provide consistency guarantees on the webref/ed tree (where SupportedType has been renamed to the well-defined DOMParserSupportedType and the interface itself been moved to the HTML standard)

The `webref/ed` tree does not really provide additional consistency guarantees. It just uses the latest version of Editor's Drafts which, more often than not, are more consistent than the sometimes outdated Working Drafts published to /TR. That said, the `webref/ed` tree can also contain invalid IDL that sometimes get introduced in Editor's Drafts...

Guarantees are enforced in the NPM package (through a set of patches that get applied to the IDL before packaging)

> At the moment, I wouldn't recommend working on top of webref/tr. @tidoust maybe we should emphasize that somehow in the README?

Yes, will do.

**Comment by jodinathan** [comment]
> in the general, you'll get the highest level of guarantees from the data in the [NPM package](https://www.npmjs.com/package/@webref/idl)

The point is that I am not using NodeJS and this is the github linked in the package, so I thought the packaged used these files.

I started only using the ED directory, however, I've found out that PaymentAddress is used but is only declared in the TR version.

**Comment by jodinathan** [comment]
> Guarantees are enforced in the NPM package (through a set of patches that get applied to the IDL before packaging)
> 

can I fetch the parsed and patched IDL from the package without using it in NodeJS?

**Comment by dontcallmedom** [comment]
you can download the tarball of files from https://registry.npmjs.org/@webref/idl/-/idl-2.2.2.tgz (and parse https://registry.npmjs.org/@webref/idl in general to know what's the latest version of and where the tarball is); its content is mostly IDL & JSON files, which a thin JS wrapper you can absolutely ignore for non-JS usage.

**Comment by jodinathan** [comment]
> > I started only using the ED directory, however, I've found out that PaymentAddress is used but is only declared in the TR version.
> 
> That's indeed one of the things that are fixed in the packaged version https://github.com/w3c/webref/blob/master/ed/idlpatches/payment-request.idl.patch

I am curious: why isn't this in the IDL and parsed files?

**Comment by dontcallmedom** [comment]
> I am curious: why isn't this in the IDL and parsed files?

Right now, the IDL and IDLparsed files kept in `ed` are the direct extracts from the original specifications, unadulterated; one reason is mostly historical (we added the curation process as part of developing the packages), the other is practical - the raw extracts are updated every 6 hours, and it would be hard to deal with the manual aspects of that curation on that basis.

But we could publish the curated files in a branch, or have them be the basis for our `w3c.github.io` version, presumably. Maybe an idea worth filing (we have a [similar one for the related browser-specs project](https://github.com/w3c/browser-specs/issues/38))

**Comment by jodinathan** [comment]
> you can download the tarball of files from https://registry.npmjs.org/@webref/idl/-/idl-2.2.2.tgz (and parse https://registry.npmjs.org/@webref/idl in general to know what's the latest version of and where the tarball is); its content is mostly IDL & JSON files, which a thin JS wrapper you can absolutely ignore for non-JS usage.

couldn't find a JSON in that tarball, only .idl files

**Comment by tidoust** [comment]
> couldn't find a JSON in that tarball, only .idl files

There are no JSON files in the `@webref/idl` package on top of `package.json`.
What is the information that you wish would be in the package?

**Comment by jodinathan** [comment]
@tidoust Dom said that the JSON within the package is more robust than the ones in this repo. So I thought in use them as my source of info.

My project is basically craw the IDL list in the JSON files to create DartLang JS bindings and publish it to the community.
I am also crawling the MDN website to add documentation to classes I am generating.

**Comment by tidoust** [comment]
Right, my question is: Which JSON files are you willing to use? The ones under [ed/idlnamesparsed](https://github.com/w3c/webref/tree/master/ed/idlnamesparsed)? The ones under [ed/idlparsed](https://github.com/w3c/webref/tree/master/ed/idlparsed)?

For the time being, we don't create curated versions of these files and they are not part of any released package. That could perhaps change in the future.

**Comment by jodinathan** [comment]
I am not sure if the ones I am using are the correct ones, but I am using idlparsed.
I also have to merge the contents idlparsed/idlNames and idlparsed/idlExtendedNames to have a full interface description.

**Comment by jodinathan** [comment]
Do you guys know if is there any fix in the JS package for ```HTMLHyperlinkElementUtils``` and ```SVGURIReference```?
They declare a ```href``` getter with different types and ```SVGAElement``` in *svg2* and *svg11* extend them both.

I am not sure how to should I treat them so I don't have inheritance problems.

**Comment by dontcallmedom** [comment]
This is apparently indeed a known issue of the SVG spec: https://github.com/w3c/svgwg/issues/312 (one of a type we should probably detect and create protection against in the context of webref)

If I understand the discussion on the issue correctly, you should the SVGURIReference definition of the `href` attribute.

**Comment by jodinathan** [comment]
> This is apparently indeed a known issue of the SVG spec: [w3c/svgwg#312](https://github.com/w3c/svgwg/issues/312) (one of a type we should probably detect and create protection against in the context of webref)
> 
> If I understand the discussion on the issue correctly, you should the SVGURIReference definition of the `href` attribute.

I should use or disregard? :-)

**Comment by dontcallmedom** [comment]
oops, "use"

**Comment by dontcallmedom** [comment]
I've filed #277 to look into releasing curated data in a non-NPM format.

**Comment by jodinathan** [comment]
I've created the JS bindings for the Dart language.
It is one file per spec and everything is automatically documented by machine-reading the MDN website.
Take a look on how nice the media stream file got: https://github.com/jodinathan/js_bindings/blob/main/lib/bindings/mediacapture_streams.dart

thanks for all your info and I will keep checking the issue for the curated data =]

**Comment by tidoust** [comment]
Curated data is now available on the `curated` branch, and published under https://w3c.github.io/webref/ed/.
