### ISSUE TITLE
Release curated data on the Web

### ISSUE THREAD

**Issue by dontcallmedom** [w3c/webref#277]
#269 made it apparent that keeping NPM-only the consistency-guarantees provided by the NPM packages had two limitations:
* it forces to go through NPM which is at best awkward for non-NPM based consumers
* it limits the impact of the curation to whatever is packaged (e.g. the raw IDL files for the WebIDL package) - there is no easy way to access the generated JSON files that derive from it

An idea @tidoust and I discussed was to use w3c.github.io/webref to publish the curated-based view of the data.

This would require:
* moving the anomaly report out of webref (which we have discussed doing for quite some time in any case)
* adopting the release workflows to make publication on the `gh-pages` branch another of their outcomes

One question that needs more thinking is how to manage versioning.

**Comment by tidoust** [comment]
Additionally, it would require generating the curated versions of folders in the first place. We don't produce the curated version of `idlnames` for the time being. It's just a matter of running the code on the curated version of the IDL, but that probably requires some adjustments to the code.

**Comment by tidoust** [comment]
Following discussions with @dontcallmedom, updated plan is to only create one view in the `curated` branch that contains all specs, except that the `ed/idlnames` and `ed/idlnamesparsed` folders in that view will be restricted to actual browser specs. It should be trivial to filter out specs that people may not be interested in other folders.

Published npm packages will also continue to be restricted to actual browser specs.

**Comment by tidoust** [comment]
I'm closing the issue as the curation job is now in place and seems to work. I wouldn't be too surprised if additional tweaks turn out to be needed but let's handle them separately.

The `@webref/idl@latest` ref will point to the right commit on the `curated` branch as soon as a new version of the `@webref/idl` package gets released (currently blocked by non-distinguishable IDL in Autoplay Policy Detection)

Same thing for the `@webref/css@latest` ref (there was a remaining bug in the release script when the `@webref/css@3.0.4` was released, so tags could not be added).

The `@webref/elements@latest` ref... does not exist yet, @dontcallmedom to create it and have it point to [`@webref/elements@1.0.4`](https://github.com/w3c/webref/releases/tag/%40webref%2Felements%401.0.4).

**Comment by dontcallmedom** [comment]
`@webref/elements@latest` now created
