### ISSUE TITLE
Elements extraction: unknown interfaces for some SVG 1.1 elements

### ISSUE THREAD

**Issue by tidoust** [w3c/webref#278]
The switch to the /TR version of SVG 1.1 reveals a bug in the elements extraction logic: the `elements` folder contains one file per spec but the `idl` folder contains one file per spec series.

The /TR version of SVG 1.1 defines interfaces that no longer exist in SVG 2 such as [`SVGTRefElement`](https://www.w3.org/TR/SVG11/text.html#InterfaceSVGTRefElement). The corresponding IDL does not appear in webref because we only extract the IDL of the "current" spec in the series, meaning SVG 2.

Ideally, we'd have the elements and interfaces from SVG 2 + the elements and interfaces from SVG 1.1 that are not defined in SVG 2.

Possible ways to solve the problem:
1. Switch to one file per specification series for the `elements` folder (+ delta specs) as done for `css` and `idl`. The SVG 1.1 elements would then no longer be extracted, which seems wrong, but then the SVG 1.1 interfaces are *not* extracted either for the time being.
2. Exclude SVG 1.1 from the `elements` extraction.
3. Define SVG 2 as a delta spec over SVG 1.1, but that is not true in practice and will likely create IDL inconsistencies as SVG 2 redefines some of the IDL defined in SVG 1.1.
4. Add an IDL patch for `SVG.idl` that adds the interfaces defined in SVG 1.1 that are not in SVG 2. To be dropped once SVG 1.1 gets obsoleted?

**Comment by tidoust** [comment]
I forgot to mention that the way this bug gets revealed in practice is that consistency tests for `@webref/elements` no longer pass, which blocks the possibility to release a new version of the package.

**Comment by dontcallmedom** [comment]
my guess is that 4. is probably our best (if somewhat painful) option

**Comment by tidoust** [comment]
The PR drops SVG 1.1 elements that have not been implemented and no longer exist in SVG 2, and adds interfaces to the IDL patch for SVG 1.1 elements that have been implemented but are no longer defined in SVG 2.

**Comment by foolip** [comment]
@dontcallmedom says this is where the decision to include old SVG IDL was made.

I'd like to revisit that, since the inclusion of IDL that isn't intended to be support in the long term (even if support remains now) makes webref harder to use in WPT.

I have a huge pile of custom IDL in mdn-bcd-collector, and this was in that pile. If there's a need for non-standard-but-supported IDL in other project too, maybe we could collect that into a separate part of webref, so that WPT could ignore it but mdn-bcd-collector could include it?

**Comment by tidoust** [comment]
Then we'll need to do "2. Exclude SVG 1.1 from the elements extraction" (or to restrict the SVG 1.1 extracts to elements that are still defined in SVG 2).

@saschanaz Do you have any need for the SVG 1.1 elements that are still supported in browsers but deprecated, and that currently appear in @webref/elements (`<altGlyph>`, `<cursor>`, `<glyphRef>`, `<font>`)?

Side note: it would be good to have the SVG WG update the [Status of this Document](https://svgwg.org/svg2-draft/#status) section of the SVG 2 spec to clarify that the document "builds upon SVG 1.1" also by dropping a few features. As written, the text suggests that nothing was dropped.

**Comment by saschanaz** [comment]
As all of the four are Safari-only, I don't need them.
