### ISSUE TITLE
If a <dfn> in a heading doesn't have an ID, link to the heading's ID instead

### ISSUE THREAD

**Issue by tabatkins** [w3c/webref#303]
A number of dfns in HTML (for example, <https://html.spec.whatwg.org/multipage/text-level-semantics.html#the-small-element>) are placed into headings and not given an ID of their own.

Shepherd, Bikeshed's current dfn source, automatically handles this by reporting the heading's ID as the link target for the dfn, which gives good results. WebRef doesn't; it simply treats these dfns as unlinkable and omits them entirely. This is currently a blocker on switching Bikeshed to using WebRef, as it means a number of useful HTML terms are no longer linkable (and this shows up in my integration tests).

WebRef should handle this situations the same way Shepherd does - if one or more dfns in a heading don't have IDs, but the heading does, take the heading's ID as the link location for those dfns.

(I also want to allow this for more arbitrarily-placed definitions, when the most appropriate landing anchor for a dfn would be the heading for its section, rather than the dfn itself. This would be useful for cases where the term being defined doesn't actually show up until a decent bit of introductory text, which is necessary context for understanding the definition itself. Linking straight to the dfn and requiring people to scroll up to find the required context isn't a great experience currently. This would be a separate feature, tho, and opt-in; we can discuss it later, I'm just providing some additional context for this issue.)

**Comment by tidoust** [comment]
As far as I can tell, the crawler does use the heading's ID in such cases (see [corresponding code in Reffy](https://github.com/w3c/reffy/blob/main/src/browserlib/extract-dfns.mjs#L228)), leading to the following entry in the dfn extract for "small" in the `html.json` extract:

```json
{
  "id": "the-small-element",
  "href": "https://html.spec.whatwg.org/multipage/text-level-semantics.html#the-small-element",
  "linkingText": [
    "small"
  ],
  "localLinkingText": [],
  "type": "element",
  "for": [],
  "access": "public",
  "informative": false,
  "heading": {
    "id": "the-small-element",
    "href": "https://html.spec.whatwg.org/multipage/text-level-semantics.html#the-small-element",
    "title": "The small element",
    "number": "4.5.4"
  },
  "definedIn": "heading"
}
```

Could the problem rather be that you're expecting a different linking text for this definition? For instance, are you trying to find an entry with the full heading's title, meaning "the small element"?

Headings appear in a separate extract for now, e.g. https://github.com/w3c/webref/blob/master/ed/headings/html.json#L1431

**Comment by tidoust** [comment]
@tabatkins I'm closing this issue as I believe Webref already handles `<dfn>` without IDs in headings. Please re-open if you think that's not the case.

**Comment by tabatkins** [comment]
Hm, I'll double-check; this was definitely causing link failures before. And no, the linking text should definitely just be "small".
