### ISSUE TITLE
Missing i18n-glossary

### ISSUE THREAD

**Issue by r12a** [w3c/webref#465]
The i18n WG would like to be able to link to definitions in https://www.w3.org/TR/i18n-glossary/ when using the xref feature of respec in their documents, but it doesn't appear that that document is searched for terms.

Can someone help?

**Comment by dontcallmedom** [comment]
we will need to add it as a source (I've filed https://github.com/w3c/browser-specs/issues/483 to that end); but to make the terms xref-visible, you'll also need to annotate the relevant `<dfn>` [with the `data-export` attribute](https://github.com/w3c/respec/wiki/data-export)

**Comment by r12a** [comment]
> to make the terms xref-visible, you'll also need to annotate the relevant <dfn> with the data-export attribute

Ok that's done in the ED https://w3c.github.io/i18n-glossary/.  I'll publish to TR when it has been added as a source.

**Comment by dontcallmedom** [comment]
https://github.com/w3c/webref/blob/main/ed/dfns/i18n-glossary.json has now the extracted definitions of the i18n-glossary document; they should appear in xref search once they run their next import (which I think happens several times a day)
