### ISSUE TITLE
ED and TR json with error

### ISSUE THREAD

**Issue by jodinathan** [w3c/webref#466]
There are a few JSON with error msgs inside: 

tr/ed [SVG11.json](https://github.com/w3c/webref/blob/3d5f29e89d33ec0dc6d10b3f081308fcc1b3f010/tr/idlparsed/SVG11.json#L8)
[tr/css-regions-1.json](https://github.com/w3c/webref/blob/3d5f29e89d33ec0dc6d10b3f081308fcc1b3f010/tr/idlparsed/css-regions-1.json#L7)
[tr/WebCryptoAPI.json](https://github.com/w3c/webref/blob/3d5f29e89d33ec0dc6d10b3f081308fcc1b3f010/tr/idlparsed/css-regions-1.json#L7)
[tr/css-font-loading-3](https://github.com/w3c/webref/blob/3d5f29e89d33ec0dc6d10b3f081308fcc1b3f010/tr/idlparsed/css-font-loading-3.json#L7)
[tr/cssom-view-1](https://github.com/w3c/webref/blob/3d5f29e89d33ec0dc6d10b3f081308fcc1b3f010/tr/idlparsed/cssom-view-1.json#L7)

**Comment by tidoust** [comment]
So, that's essentially the same problem as in #269 :)

The IDL that gets parsed here is the raw IDL extracted from the specs, and some specs define invalid IDL (especially those under /TR which tend to be less frequently updated).

The IDL patches under `ed/idlpatches` contain the necessary fixes to make the IDL valid, but we don't yet have an easy-to-access view of the curated data. Good news is that I'm now working on #277 to create a `curated` branch with the patched IDL and `idlparsed` extracts without errors.

FYI, we're not planning to maintain IDL patches for the "tr" part of the data at this stage.

**Comment by jodinathan** [comment]
I will remove the "tr" dir from my crawler, thanks for the info.  

regarding #277, any estimated date?

**Comment by tidoust** [comment]
#277 is now done. Curated data is available on the `curated` branch and published under https://w3c.github.io/webref/ed/

**Comment by jodinathan** [comment]
so this dir will be updated automatically https://github.com/w3c/webref/tree/main/ed ?

**Comment by tidoust** [comment]
Not the ED dir in the `main` branch. The `main` branch remains unchanged.

The [ED dir in the `curated` branch](https://github.com/w3c/webref/tree/curated/ed) will be updated with fixes. This is done automatically whenever the `main` branch is updated... provided that patches still apply and that tests pass. If some patch no longer applies, or if some test fails, a manual intervention will be necessary to update the patches and resume the curation.
