### ISSUE TITLE
Reflect object?

### ISSUE THREAD

**Issue by jodinathan** [w3c/webref#473]
Can't seem to find the `Reflect` object and its members like `deleteProperty`. Is it in the `ed` somewhere?

**Comment by jodinathan** [comment]
sorry, I didn't know or remembered that.  

Do you happen to know if there is any json-like specification for ecmascript?

**Comment by tidoust** [comment]
There may be but I'm not aware of any. If there is one, it seems unlikely that it gets generated automatically from the spec (given that the spec is hard to process automatically)

**Comment by dontcallmedom** [comment]
a couple of additional thoughts:
* the need for formal data from the ecmascript spec may be worth [reporting to TC39](https://github.com/tc39/ecma262) 
* while I also don't believe there is an automated extract, a likely reliable source is the [TypeScript schemas maintained by Microsoft](https://github.com/microsoft/TypeScript/blob/main/lib/lib.es5.d.ts) - I haven't tested it, but I assume they should be translatable into JSON with e.g. https://www.npmjs.com/package/typescript-json-schema

(the fact that the need to maintain this typing information also fulfills a need for TypeScript might be a useful argument to bring the TC39 discussion)
