### ISSUE TITLE
Migrate reffy-reports repo to w3c organization

### ISSUE THREAD

**Issue by tidoust** [w3c/webref#52]
Tasks to perform:

- [x] Find a way to redirect `https://tidoust.github.io/reffy-reports/` URLs to new destination? There may be external projects that actually use the `https://tidoust.github.io/reffy-reports/` URLs for now and it would be good to make sure that the migration is transparent for them. But is there a magic solution to create redirects for all existing files? Actually, is there a good solution to create redirects for non-HTML files?
=> done in https://github.com/tidoust/tidoust.github.io/commit/25f8051b0928f066cafa6f2ef155d85ee4a0c181
- [x] Migrate or create target repo under w3c organization. If people would fancy a new name, now would be a good time...
=> new [w3c/webref](https://github.com/w3c/webref) repo created
- [x] Make sure that Travis CI and job actions are enabled on the target repo
- [x] Update URL in [.travis.yml](https://github.com/tidoust/reffy-reports/blob/master/.travis.yml#L22)
=> see #53 
- [x] Update source URL for commit message in [sync.js](https://github.com/tidoust/reffy-reports/blob/master/wpt-sync/sync.js#L297)
=> see #53
- [x] Make sure that the target repo has a [CONFIG_JSON secret](https://github.com/tidoust/reffy-reports/settings/secrets)... or simply update the GitHub workflow not to require that file anymore. Reffy no longer depends on the W3C API, so it no longer needs a W3C API key!
=> dropped in https://github.com/tidoust/reffy-reports/commit/993e7ef51e925adfcb9f63d7e9c1a99f98e52a39
- [x] Create the right `GH_TOKEN` secret under Travis CI for the target repo as [done for tidoust/reffy-reports](https://travis-ci.org/github/tidoust/reffy-reports/settings) for the auto generation of PRs to WPT (requires secret from @foolip as I don't think the old secret can be copied over)

Anything missing?

Cc @dontcallmedom, @foolip

**Comment by dontcallmedom** [comment]
I don't think there is a way to address the redirects (or least, no cheap way to do so, and I don't think the number of impacted people or projects to be such to be worth of using more expensive ways).

Here are some proposed names for the repo as we migrate it to w3c:
* webology
* speca-sutra
* web-isindex
* webopedia
* encycloweb
* webography
* web-atlas
* webref
* web-dictionary 
* weboscope

**Comment by tidoust** [comment]
> I don't think there is a way to address the redirects (or least, no cheap way to do so, and I don't think the number of impacted people or projects to be such to be worth of using more expensive ways).

OK, I prepared a short script that will create the right files (meaning all `.json`, `.idl`, `.md` and `.html` files that are generated in reffy-reports) in https://github.com/tidoust/tidoust.github.io with a human-readable comment in each file that a manual redirect is needed...

> Here are some proposed names for the repo as we migrate it to w3c:

Some of the names are used in other projects (webology, webopedia). Others are a bit abstract to my taste (webography, web-atlas, weboscope).

I like **webref** for its simplicity and the implicit "reference" to specref (specref is a database of specs, webref is a database of semantic info extracted from the specs themselves). I note @darobin's old [webref repo](https://github.com/darobin/webref) that probably served as ancestor for Specref...

Alternatively, I like the idea of naming the project from the obsolete `<isindex>` HTML element :) It does illustrate the need to track specifications.

**Comment by dontcallmedom** [comment]
let's go with **webref** - boring, but easy to recall and type

**Comment by foolip** [comment]
Isn't reffy-reports a pretty good name? Or something starting with reffy, to make the connection clear?

Would it help to migrate Travis to GitHub Actions before this? If so I can try doing that.

**Comment by tidoust** [comment]
> Isn't reffy-reports a pretty good name? Or something starting with reffy, to make the connection clear?

That's the alternative. Either keep the name which puts the focus on the tool that produces the data, or switch to a new name to put the focus on the data itself. One argument in favor of switching focus to the data is that it may appeal to more people than the tool itself. I'm leaning towards switching...


> Would it help to migrate Travis to GitHub Actions before this? If so I can try doing that.

We would still need to store the token for autofoolip as a secret somewhere, right? It would indeed be good to use only one CI system down the road, but that does not seem needed to transfer the repo.

**Comment by foolip** [comment]
Alright, I'll not spend any time on the CI setup at this point.

**Comment by tidoust** [comment]
Repo migrated and build tasks seem to be running fine (although note bugs #54 and #55). Closing this issue as a result.

Further improvements include:
- renaming the branches for Web Platform Tests, handled in #57.
- updating the preamble that appears in IDL files, handled in https://github.com/tidoust/reffy/pull/393
