### ISSUE TITLE
Incorrect Travis CI Build URL?

### ISSUE THREAD

**Issue by tidoust** [w3c/webref#55]
The build URL that appears in PR created by `sync.js` seems incorrect. [Last one](https://github.com/web-platform-tests/wpt/pull/25330) was:
  https://travis-ci.org/w3c/webref/builds/723107475
... but that build number does not exist. Right build number and right build URL should rather be:
  https://travis-ci.com/github/w3c/webref/builds/182272553

I do not know why there exists a mismatch in the build numbers. However, there seems to be a [`TRAVIS_BUILD_WEB_URL` environment variable](https://docs.travis-ci.com/user/environment-variables/#Default-Environment-Variables). @foolip, any reason not to use that in `.travis.yml` instead of attempting to build the URL ourselves?

**Comment by foolip** [comment]
Using `TRAVIS_BUILD_WEB_URL` sounds great, perhaps it didn't exist when I made this, or I just didn't find it.

**Comment by tidoust** [comment]
Closing this since we're now more aiming at dropping the job than at improving it.
