### ISSUE TITLE
Publish package about events?

### ISSUE THREAD

**Issue by foolip** [w3c/webref#593]
In https://github.com/mdn/browser-compat-data/issues/15345 we have seen that there's no machine readable information about which events fire on which interfaces, whether they bubble, what interfaces are used, etc. This information isn't generally machine readable in specs, but could be useful to tooling.

Could there be a webref package for this, similar to `@webref/elements`?

**Comment by dontcallmedom** [comment]
We had some exploration on extracting data on this from specs https://github.com/w3c/reffy/issues/772

Are you suggesting collecting the data manually and releasing in a webref package or something else?
