### ISSUE TITLE
Automatically delete files that have no matching specs in browser-specs

### ISSUE THREAD

**Issue by dontcallmedom** [w3c/webref#66]
via a pull request

**Comment by foolip** [comment]
Ah yes, now that we have the list in browser-specs, we don't have the risk of deleting things just because the scrape failed. Sound good!

**Comment by dontcallmedom** [comment]
I was initially thinking of a cron job that would push the to-be-deleted files as a pull request; but looking a bit more into this, I'm thinking the following would work better:
* when reffy generates the extracts, have it always generate a file even when hitting an error, but have it be an empty file for the error case
* update the [rsync that populates webref](https://github.com/w3c/webref/blob/984fa94cd346409f9cddcf616346d9637eaa83fd/.github/workflows/update-ed.yml#L37) to use `--delete` (so that it delete files that aren't produced by reffy) and `--min-size=1` (so that it doesn't overwrite existing files with empty files coming from a parsing error)

(the problem with the initial approach is that it means redoing some of the mapping from browser-specs to the filesystems output that reffy is already handling; probably not a huge deal from a code perspective, but it feels brittle)

thoughts? cc @tidoust

**Comment by tidoust** [comment]
> when reffy generates the extracts, have it always generate a file even when hitting an error, but have it be an empty file for the error case

Isn't the "error case" is going to be the same as the "no content to extract" case in most cases, meaning cases when the extraction logic simply fails to extract meaningful content?

If so, if you apply this change, you're going to make Reffy create IDL files for each and every spec, including e.g. CSS specs that don't have any IDL. These files would be empty and, thanks to the second change, they would not end up in webref, so perhaps that's ok, they'll just pollute local results of a crawl.

The empty files should just not end up being referenced in [index.json](https://github.com/w3c/webref/blob/master/ed/index.json).

Alternatively, aren't all specs going to appear in [index.json](https://github.com/w3c/webref/blob/master/ed/index.json) file, even when there are errors? If so, you could use that file, which contains shortnames (and series shortnames), to identify the extracts that don't correspond to any of the entries in index.json.
