### ISSUE TITLE
Check CSS/IDL extracts against dfns extracts

### ISSUE THREAD

**Issue by tidoust** [w3c/webref#67]
All terms defined in CSS and IDL extracts should have a corresponding definition in dfns extracts. Checking this invariant automatically would allow to detect cases where e.g. definitions of IDL terms are missing.

See additional context and discussion in https://github.com/tidoust/reffy/pull/419

**Comment by foolip** [comment]
This would be great! I've pondered just in the past few days if I'd get the same terms by parsing IDL and by looking at definitions, and it sounds like it's not guaranteed.

**Comment by tidoust** [comment]
Done through https://github.com/tidoust/reffy/pull/439. See report in https://github.com/tidoust/reffy/pull/439#issuecomment-723122416

The analysis still needs to be integrated in the anomalies report. This is being tracked in https://github.com/tidoust/reffy/issues/447

**Comment by tidoust** [comment]
The analysis has been integrated in the anomalies report, see for instance the [report per issue](https://w3c.github.io/webref/ed/perissue.html#no-definition-for-css-properties). No real outstanding problem found, most of the reported "errors" are due to specs not yet supporting the right data model for definitions, notably in the HTML spec.
