### ISSUE TITLE
Documents of css specification

### ISSUE THREAD

**Issue by ChijinZ** [w3c/webref#747]
Hi. I would like to write a parser to parse the css specifications in the ``ed/css`` folder. But I'm not sure if I fully understand the ``value`` field of those json files. For example:

```json
"grid": {
      "name": "grid",
      "value": "<'grid-template'> | <'grid-template-rows'> / [ auto-flow && dense? ] <'grid-auto-columns'>? | [ auto-flow && dense? ] <'grid-auto-rows'>? / <'grid-template-columns'>",
}
```

Is there any documents out there to explain the definition sof ``/``, ``?``, ``&&`` symbols? Or is there any off-the-shelf parsers for  reference?

**Comment by dontcallmedom** [comment]
the syntax is the one defined in [CSS Values and Units Module](https://drafts.csswg.org/css-values/#value-defs); it can be parsed by the [csstree library](https://github.com/csstree/csstree) as described in the [@webref/css package guarantees](https://github.com/w3c/webref/tree/main/packages/css#guarantees)
