### ISSUE TITLE
css-images lacks object-position from css-images-3

### ISSUE THREAD

**Issue by saschanaz** [w3c/webref#77]
It seems it currently refers to css-images-4 but AFAICT it's an extension of Level 3. Maybe there should be `css-images` and `css-images-4`, just as there are `css-grid` and `css-grid-3`?

**Comment by dontcallmedom** [comment]
I've filed https://github.com/w3c/csswg-drafts/issues/5804 to get clarity on the relationship between levels 3 and 4; if level 4 is meant as a delta spec, we can handle it the same way as css-grid is handled.

**Comment by saschanaz** [comment]
I think this is now resolved, thanks!
