### ISSUE TITLE
Invalid CSS value type name `identifiers|<identifier>`

### ISSUE THREAD

**Issue by cdoublev** [w3c/webref#808]
The following type value is extracted from [CSS 2](https://drafts.csswg.org/css2/#value-def-identifier):

https://github.com/w3c/webref/blob/b93beefbba271fa7870f2611b43aa0834095b9aa/ed/css/CSS.json#L2773-L2776

The name is taken from the `data-lt` (linking text) HTML attribute. I guess `<identifier>` should be the name (which is now `<ident>` in "post-CSS2", ie. in CSS Values 4) and `identifiers` is some sort of a plural hint.

This seems to be the only `value` for which this issue occurs, among all specs, so it may be easier to fix it in CSS 2 than with a specific patch in `w3c/webref`.

**EDIT**

Sorry, I should have created this issue on `w3c/reffy`. Feel free to close/move it. 

There are also a few problems with the values extracted from CSS Easing. For example, `<linear-easing-function>`, `linear()`, etc... do not exist. I will wait for your comment before creating a dedicated issue on `w3c/reffy`, because I do not have a global understanding on how values are extracted yet, but they may be related to how the `data-lt` and other attributes are parsed.

**Comment by tidoust** [comment]
> The name is taken from the `data-lt` (linking text) HTML attribute. I guess `<identifier>` should be the name (which is now `<ident>` in "post-CSS2", ie. in CSS Values 4) and `identifiers` is some sort of a plural hint.

Ah, I wasn't expecting any spec to create multiple linking terms for a definition of type `type`, one for prose-like references and one for syntax references. I'll update the logic in Reffy to pick up the value enclosed in `<` and `>` characters since syntax is what we're interested in for the extract.

> There are also a few problems with the values extracted from CSS Easing. For example, <linear-easing-function>, linear(), etc... do not exist.

What do you mean by "[they] do not exist"? They seem both [defined in the spec](https://drafts.csswg.org/css-easing-2/#funcdef-linear) and [present in the extract](https://github.com/w3c/webref/blob/3137599f81a35ae59eee9311a7ff1aca597e4c8d/ed/css/css-easing.json#L24)

(I see extraction fails to produce a `value="linear(<linear-stop-list>)` property for `linear()` though, which is what I would expect to find, I'll look into it)

**Comment by cdoublev** [comment]
> > There are also a few problems with the values extracted from CSS Easing. For example, , linear(), etc... do not exist.
> 
> What do you mean by "[they] do not exist"? They seem both [defined in the spec](https://drafts.csswg.org/css-easing-2/#funcdef-linear) and [present in the extract](https://github.com/w3c/webref/blob/3137599f81a35ae59eee9311a7ff1aca597e4c8d/ed/css/css-easing.json#L24)

I was looking in CSS Shapes 1... sorry.

**Comment by tidoust** [comment]
Fixed in Reffy and latest crawl now has the right name:

https://github.com/w3c/webref/blob/48877caad497ef1353b3468d24fbaf6a08dc47a4/ed/css/CSS.json#L2773-L2776

Thanks for the report!

> (I see extraction fails to produce a value="linear(<linear-stop-list>) property for linear() though, which is what I would expect to find, I'll look into it)

Also fixed.

**Comment by cdoublev** [comment]
`identifiers` is [extracted again](https://github.com/w3c/webref/blob/7d1b2469732f6169e05da2bb6a767499a4f3a529/ed/css/CSS.json#L2854) after [this change](https://github.com/w3c/reffy/commit/72cd2deb607e232c8cdef582f4f28e4cce2d2222). 

I think `textContent` should only be tested as a last resort [here](https://github.com/w3c/reffy/blob/90bc9eb7ebcb3c23d73d2e1e188ac8370670f08b/src/browserlib/extract-cssdfn.mjs#L559), and [the corresponding test](https://github.com/w3c/reffy/blob/90bc9eb7ebcb3c23d73d2e1e188ac8370670f08b/tests/extract-css.js#L1220) should have the same value in `data-lt` and in the `dfn.textContent`: `identifiers`.
