### ISSUE TITLE
Missing/mismatched specs between tr and ed files

### ISSUE THREAD

**Issue by tabatkins** [w3c/webref#842]
When comparing <https://raw.githubusercontent.com/w3c/webref/main/tr/index.json> and <https://raw.githubusercontent.com/w3c/webref/main/ed/index.json>, linking together the entries in the two documents by shortname almost entirely works, but there are a handful of specs that claim to have both "release" and "nightly" versions, but only exist in one of those documents.

One is 'contact-picker-1' in the ED data and 'contact-api' in the TR data, which seems to be just a mismatch between the CG name and the published name.

The rest are all the CSS specs that [I recently asked to have added to the DB](https://github.com/tabatkins/bikeshed/issues/2431#issuecomment-1373992354) - they're present in the ED data but missing from the TR data. I presume whatever added them just wasn't updated in both places.

**Comment by tidoust** [comment]
Right, crawls of "release" versions of the specs were only done once per week, so data was not yet available for newly added/updated specs. I triggered a crawl manually. Data for all specs should now be available. I'm closing the issue accordingly, but please shout if something's still missing!

I also changed the frequency of release crawls to once per day. Nightly crawls run 4 times per day so release data may still be slightly behind nightly data. I'll try to improve crawling rules to end up with the same frequency for both types of crawls (release crawl currently fetches nightly versions of specs that don't have a proper release version, whereas we already have that data from the nightly crawl).

**Comment by tabatkins** [comment]
Ah cool, looks good to me. Having the frequency match isn't strictly necessary, fwiw - my code handles it fine, I just had a check for this exact condition in case there were any data issues. But it is nice, certainly.
