### ISSUE TITLE
Missing ECMAScript "abstract op" definitions

### ISSUE THREAD

**Issue by tabatkins** [w3c/webref#888]
Now that ES is linkable via WebRef, I'm trying to trim WebIDL's massive list of manual anchors. However, it looks like all the "abstract op" definitions from ES aren't in WebRef. The markup looks like it should be acceptable to detect and link to, so I presume the extraction code is just missing this category.

For example, see AllocateArrayBuffer() <https://tc39.es/ecma262/#sec-allocatearraybuffer> - it's an `<emu-clause id=... type=abstract-op>` containing an `h1` with the algo name.

These should export as `abstract-op` in the linking database, ideally as just the name itself (no parens or arguments), tho it's acceptable if the parens and/or arguments are present in additional linking texts. That is, for something like AllocateArrayBuffer, I expect "AllocateArrayBuffer" as the linking text, but I'm okay with `["AllocateArrayBuffer", "AllocateArrayBuffer()", AllocateArrayBuffer(constructor, byteLength)"]` if y'all prefer doing it that way. (This is because whether the arguments are passed in a function-like way or just in prose varies, so I purposely don't capture the distinction.)

<details>
<summary>The full list of abstract ops WebIDL references that aren't in WebRef:</summary>
<pre>
abs
AllocateArrayBuffer
ArrayCreate
Call
CanonicalNumericIndexString
Completion
Construct
CreateArrayFromList
CreateBuiltinFunction
CreateDataProperty
CreateIteratorFromClosure
CreateIterResultObject
CreateMethodProperty
DefinePropertyOrThrow
DetachArrayBuffer
floor
FromPropertyDescriptor
GeneratorYield
Get
GetFunctionRealm
GetIterator
GetMethod
GetValueFromBuffer
IfAbruptRejectPromise
IsAccessorDescriptor
IsCallable
IsConstructor
IsDataDescriptor
IsDetachedBuffer
IsInteger
IsSharedArrayBuffer
IteratorStep
IteratorValue
MakeBasicObject
max
min
NewPromiseCapability
OrdinaryDefineOwnProperty
OrdinaryGetOwnProperty
OrdinaryObjectCreate
OrdinarySetWithOwnDescriptor
PerformPromiseThen
ProxyCreate
Set
SetFunctionLength
SetFunctionName
SetImmutablePrototype
SetIntegrityLevel
SetValueInBuffer
ToBigInt
ToBoolean
ToInt32
ToNumber
ToNumeric
ToObject
ToPropertyDescriptor
ToString
ToUint32
Type
Yield
</pre>
</details>

**Comment by tidoust** [comment]
That sounds reasonable.

The abstract operations are in Webref already but in "long form" only, e.g. with `["AllocateArrayBuffer(constructor, byteLength)"]` as linking text. What's missing is creating the shorter versions of the linking texts. We don't create alternate linking texts ourselves for other specs because the spec is supposed to take care of it, but ECMAScript does not follow the usual model.

I note that the same problem exists with methods, e.g. [`bind(thisArg, ...args)`](https://tc39.es/ecma262/multipage/fundamental-objects.html#sec-function.prototype.bind).

**Comment by tabatkins** [comment]
> The abstract operations are in Webref already but in "long form" only

Hm, not all of them are. ToUint32, for example, is missing from the data.

> We don't create alternate linking texts ourselves for other specs because the spec is supposed to take care of it, but ECMAScript does not follow the usual model.

Ah, I can bug ECMAScript to fix that; Bikeshed goes out of its way to generate those alternate forms, and it probably should be the generator's responsibility.

**Comment by tabatkins** [comment]
Actually, wait, Bikeshed only generates variant linking texts for optional arguments. To capture the no-arg linking syntax, Bikeshed does some database massaging to map functions to argless forms (this isn't generally safe, since there can be conflicts in the argless forms that aren't present in the actual definitions).

So I can extend that code to handle abstract ops myself, actually. But we are still missing some abstract ops; I don't have an exhaustive list but hopefully there's something obviously wrong that ToUint32 reveals.

**Comment by tidoust** [comment]
> Ah, I can bug ECMAScript to fix that; Bikeshed goes out of its way to generate those alternate forms, and it probably should be the generator's responsibility.

Right, as I started to look into this today, I realized that generating alternate forms automatically could be a perilous exercise, and would probably best be left to the author (and underlying generator), and not something that a crawler should do. That said, all abstract op definitions seem to have an `aoid` attribute that gives the name of the abstract operation without parentheses, so I was planning to use that.

> Hm, not all of them are. ToUint32, for example, is missing from the data.

I'll look into it. I noted that there are other definitions that are not properly extracted, or not associated with the right parent object. For instance, the crawler is totally confused by [Environment records methods](https://tc39.es/ecma262/multipage/executable-code-and-execution-contexts.html#sec-environment-records)) for now.

**Comment by tidoust** [comment]
>  That said, all abstract op definitions seem to have an aoid attribute that gives the name of the abstract operation without parentheses, so I was planning to use that.

The crawler now takes the `aoid` attribute into account to generate the linking text, yielding `["AllocateArrayBuffer", "AllocateArrayBuffer(constructor, byteLength)"]` for example. The `aoid` attribute is defined most of the time, but not always though, so some abstract op definitions still only have the longer form.


> Hm, not all of them are. ToUint32, for example, is missing from the data.

The `ToUInt32` methods and friends were not being picked up because of too restrictive a regular expression that did not expect digits to be used in method names. Now fixed. The extraction logic remains somewhat clunky. Let me know if some definitions are still missing.


> I noted that there are other definitions that are not properly extracted, or not associated with the right parent object. For instance, the crawler is totally confused by [Environment records methods](https://tc39.es/ecma262/multipage/executable-code-and-execution-contexts.html#sec-environment-records)) for now.

Also fixed.
