### ISSUE TITLE
%s in IDs are incorrectly left unescaped in URLs

### ISSUE THREAD

**Issue by tabatkins** [w3c/webref#889]
See, for example, <https://github.com/w3c/webref/blob/main/tr/dfns/ecmascript.json#L5810>. An unencoded `%` in a URL is a parsing error, and causes HTML validation errors. These %s in IDs should be encoded as `%25` when generating URLs.

**Comment by tidoust** [comment]
For some reason, I had managed to convince myself that the `toString()` method of the `URL` object was taking care of this automatically... Fixed in Reffy and Webref data.
