### ISSUE TITLE
Index of IDL names

### ISSUE THREAD

**Issue by dontcallmedom** [w3c/webref#89]
`ed/index.json` (and its equivalent for TR) give an entry point to most of the relevant files in webref, but that's not the case for `idlnames` and `idnamesparsed`. Maybe we should have an index.json in these subdirectories, or add an entry in the main index.json that can serve as an index for them?

**Comment by tidoust** [comment]
I don't disagree. I didn't add entries to the main `index.json` file because I felt this would make the file grow significantly, and I didn't add an `index.json` file in `idlnamesparsed` so that it wouldn't be confused with an actual IDL name. But we can probably find a middle ground somewhere.

**Comment by dontcallmedom** [comment]
how about `ed/idlnames.json` to serve as the list if names that can be used to reconstruct file paths?
